# Generated by Django 2.2.7 on 2019-12-02 09:28

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0004_auto_20191202_0923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='face_codes',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=129, null=True), size=128),
        ),
    ]
