# Generated by Django 2.2.7 on 2019-12-02 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0007_auto_20191202_0939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='photo',
            field=models.ImageField(default='zhora.jpg', upload_to='uploads/'),
        ),
    ]
