# Generated by Django 2.2.7 on 2019-12-02 10:10

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0011_auto_20191202_1004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='face_codes',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(default=0), size=128),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='photo',
            field=models.ImageField(default='zhora.jpg', upload_to=''),
        ),
    ]
