# Generated by Django 2.2.7 on 2019-12-02 10:18

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0013_auto_20191202_1017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='face_codes',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(blank=True, default=0, null=True), blank=True, null=True, size=128),
        ),
    ]
