# Generated by Django 2.2.7 on 2019-12-06 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0015_auto_20191202_1018'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
